cache:
  paths:
    - .m2/repository

variables:
  # This will supress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # `installAtEnd` and `deployAtEnd`are only effective with recent version of the corresponding plugins.
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"


stages:
  - test
  - build
  - deploy

test:
  stage: test
  maven-build:
    image: maven:3-jdk-8
    stage: build
    script: "mvn $MAVEN_CLI_OPTS test-compile"

build:
  stage: build
  maven-build:
    image: maven:3-jdk-8
    stage: build
    script: "mvn $MAVEN_CLI_OPTS package docker:build -DskipTests"
    artifacts:
      paths:
        - target/*.jar

deploy_test:
  stage: deploy
  script:
    - echo "Deploy to test server"
  environment:
    name: test
    url: http://test
  only:
  - master

deploy_prod:
  stage: deploy
  script:
    - echo "Deploy to production server"
  environment:
    name: prod
    url: http://prod
  when: manual
  only:
  - master
