stages:
  - test
  - build
  - deploy

test:
  stage: test
  script: echo "Running tests"

build:
  stage: build
  script: echo "Building the app"

deploy_test:
  stage: deploy
  script:
    - echo "Deploy to test server"
  environment:
    name: test
    url: http://test
  only:
  - master
